import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import pg from "pg";
import { PostgresPersistence } from "./persistence/postgres.js";

test("Adapter-declared legacy columns migrate idempotently and retain rollback projections", { skip: !process.env.POSTGRES_TEST_URL }, async (t) => {
  const root = new pg.Pool({ connectionString: process.env.POSTGRES_TEST_URL });
  const schema = `migration_${randomUUID().replaceAll("-", "")}`;
  await root.query(`create schema ${schema}`);
  const url = new URL(process.env.POSTGRES_TEST_URL!);
  url.searchParams.set("options", `-csearch_path=${schema}`);
  const persistence = new PostgresPersistence(url.toString());
  t.after(async () => { await persistence.close(); await root.query(`drop schema ${schema} cascade`); await root.end(); });
  await persistence.initialize();
  const now = new Date().toISOString();
  await persistence.createApp({ id: "sample", name: "Sample", description: "", authAdapterId: "none", status: "active", createdAt: now, updatedAt: now });
  await persistence.saveAppVersion({ id: "old", appId: "sample", version: "1.0.0", buildId: "old", packages: [], imageReference: null, status: "uploaded", createdAt: now, activatedAt: null });
  const artifact = { file: "model.zip", sha256: "a".repeat(64), size: 42 };
  await persistence.pool.query("alter table app_versions add column old_payload jsonb");
  await persistence.pool.query("update app_versions set old_payload=$1::jsonb where id='old'", [JSON.stringify(artifact)]);
  await persistence.createApp({ id: "other", name: "Other", description: "", authAdapterId: "none", status: "active", createdAt: now, updatedAt: now });
  await persistence.saveAppVersion({ id: "foreign", appId: "other", version: "1.0.0", buildId: "old", packages: [], imageReference: null, status: "uploaded", createdAt: now, activatedAt: null });
  await persistence.pool.query("update app_versions set old_payload=$1::jsonb where id='foreign'", [JSON.stringify(artifact)]);
  const options = { legacyPackageColumns: { sample: { model: "old_payload" } } };
  await persistence.initialize(options);
  const first = await persistence.getAppVersion("old");
  await persistence.initialize(options);
  assert.deepEqual(await persistence.getAppVersion("old"), first);
  assert.deepEqual(first?.packages, [{ key: "model", artifact }]);
  assert.equal("old_payload" in first!, false);
  assert.deepEqual((await persistence.getAppVersion("foreign"))?.packages, []);
  const replacement = { ...artifact, size: 43 };
  await persistence.saveAppVersion({ ...first!, packages: [{ key: "model", artifact: replacement }] });
  assert.deepEqual((await persistence.pool.query("select old_payload from app_versions where id='old'")).rows[0].old_payload, replacement);
  await persistence.saveAppVersion({ ...first!, id: "image", version: "2.0.0", sourceKind: "image", packages: [], imageReference: `sha256:${"b".repeat(64)}`, runtimeContract: "sample-v1", status: "image_ready" });
  assert.equal((await persistence.getAppVersion("image"))?.sourceKind, "image");
  await persistence.initialize(options);
  assert.deepEqual((await persistence.getAppVersion("image"))?.packages, []);
  await assert.rejects(persistence.initialize({ legacyPackageColumns: { sample: { slot: "packages" } } }), /legacy_package_column_invalid/);
});
